backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: "posts/{{year}}/{{month}}/{{slug}}"
    preview_path_date_field: "update_on"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Author", name: "author", widget: hidden, default: "YohJawa"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Header Image", name: "image", widget: "image", required: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: false}
      - {label: "Sharing", name: "share", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "hidden", type: "post"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
    editor:
      preview: false
    summary: "Version: {{version}} - {{title}}"
   
